name: Build and release portable

on:
  push:
    branches:
      - main
      - 'Feature/*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 cryptography openai

      - name: Create .env from secrets
        run: |
          echo AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} >> .env
          echo AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} >> .env
          echo AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }} >> .env

      - name: Generate secure credentials
        run: python setup_keys.py

      - name: Build executable
        shell: pwsh
        run: |
          pyinstaller --onefile --windowed `
            --add-data ".env.secure;." `
            --add-data ".key;." `
            ai_adventure.py

      - name: Package portable zip
        shell: pwsh
        run: |
          Copy-Item .env.secure dist/
          Copy-Item .key dist/
          Compress-Archive -Path dist\* -DestinationPath ai_adventure_portable.zip

      - name: Release portable build
        uses: softprops/action-gh-release@v1
        with:
          name: Build ${{ github.run_number }}
          tag_name: build-${{ github.run_number }}
          files: ai_adventure_portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
